def is_prime(n):
    
    if n < 2:
        return False
    for k in range(2, n - 1):
        if n % k == 0:
            return False
    return True





def test():

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(25) == False  # 25 is not a prime number
    assert is_prime(29) == True   # 29 is a prime number
    assert is_prime(37) == True   # 37 is a prime number
    assert is_prime(40) == False  # 40 is not a prime number
    assert is_prime(49) == False  # 49 is not a prime number

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(101) == True
    assert is_prime(13441) == False
    assert is_prime(61) == True

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(0) == False
    assert is_prime(-5) == False
    assert is_prime(25) == False
    assert is_prime(29) == True
    assert is_prime(97) == True
    assert is_prime(100) == False

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(101) == True # Test case to detect the change in the faulty code
    assert is_prime(13441) == True # Test case to detect the change in the faulty code
    assert is_prime(61) == True # Test case to detect the change in the faulty code

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(21) == False
    assert is_prime(22) == False
    assert is_prime(23) == True
    assert is_prime(24) == False
    assert is_prime(25) == False
    assert is_prime(26) == False
    assert is_prime(27) == False
    assert is_prime(28) == False
    assert is_prime(29) == True
    assert is_prime(30) == False
    assert is_prime(31) == True
    assert is_prime(32) == False
    assert is_prime(33) == False
    assert is_prime(34) == False
    assert is_prime(35) == False
    assert is_prime(36) == False
    assert is_prime(37) == True
    assert is_prime(38) == False
    assert is_prime(39) == False
    assert is_prime(40) == False
    assert is_prime(41) == True
    assert is_prime(42) == False
    assert is_prime(43) == True
    assert is_prime(44) == False
    assert is_prime(45) == False
    assert is_prime(46) == False
    assert is_prime(47) == True
    assert is_prime(48) == False
    assert is_prime(49) == False
    assert is_prime(50) == False
    assert is_prime(51) == False
    assert is_prime(52) == False
    assert is_prime(53) == True
    assert is_prime(54) == False
    assert is_prime(55) == False
    assert is_prime(56) == False
    assert is_prime(57) == False
    assert is_prime(58) == False
    assert is_prime(59) == True
    assert is_prime(60) == False
    assert is_prime(61) == True
    assert is_prime(62) == False
    assert is_prime(63) == False
    assert is_prime(64) == False
    assert is_prime(65) == False
    assert is_prime(66) == False
    assert is_prime(67) == True
    assert is_prime(68) == False
    assert is_prime(69) == False
    assert is_prime(70) == False
    assert is_prime(71) == True
    assert is_prime(72) == False
    assert is_prime(73) == True
    assert is_prime(74) == False
    assert is_prime(75) == False
    assert is_prime(76) == False
    assert is_prime(77) == False
    assert is_prime(78) == False
    assert is_prime(79) == True
    assert is_prime(80) == False
    assert is_prime(81) == False
    assert is_prime(82) == False
    assert is_prime(83) == True
    assert is_prime(84) == False
    assert is_prime(85) == False
    assert is_prime(86) == False
    assert is_prime(87) == False
    assert is_prime(88) == False
    assert is_prime(89) == True
    assert is_prime(90) == False
    assert is_prime(91) == False
    assert is_prime(92) == False
    assert is_prime(93) == False
    assert is_prime(94) == False
    assert is_prime(95) == False
    assert is_prime(96) == False
    assert is_prime(97) == True
    assert is_prime(98) == False
    assert is_prime(99) == False
    assert is_prime(100) == False
    assert is_prime(101) == True
    assert is_prime(102) == False
    assert is_prime(103) == True
    assert is_prime(104) == False
    assert is_prime(105) == False
    assert is_prime(106) == False
    assert is_prime(107) == True
    assert is_prime(108) == False
    assert is_prime(109) == True
    assert is_prime(110) == False
    assert is_prime(111) == False
    assert is_prime(112) == False
    assert is_prime(113) == True
    assert is_prime(114) == False
    assert is_prime(115) == False
    assert is_prime(116) == False
    assert is_prime(117) == False
    assert is_prime(118) == False
    assert is_prime(119) == False
    assert is_prime(120) == False
    assert is_prime(121) == False
    assert is_prime(122) == False
    assert is_prime(123) == False
    assert is_prime(124) == False
    assert is_prime(125) == False
    assert is_prime(126) == False
    assert is_prime(127) == True
    assert is_prime(128) == False
    assert is_prime(129) == False
    assert is_prime(130) == False
    assert is_prime(131) == True
    assert is_prime(132) == False
    assert is_prime(133) == False
    assert is_prime(134) == False
    assert is_prime(135) == False
    assert is_prime(136) == False
    assert is_prime(137) == True
    assert is_prime(138) == False
    assert is_prime(139) == True
    assert is_prime(140) == False
    assert is_prime(141) == False
    assert is_prime(142) == False
    assert is_prime(143) == False
    assert is_prime(144) == False
    assert is_prime(145) == False
    assert is_prime(146) == False
    assert is_prime(147) == False
    assert is_prime(148) == False
    assert is_prime(149) == True
    assert is_prime(150) == False

    assert is_prime(22) == False
    assert is_prime(23) == True
    assert is_prime(24) == False
    assert is_prime(25) == False
    assert is_prime(26) == False
    assert is_prime(27) == False
    assert is_prime(28) == False
    assert is_prime(29) == True
    assert is_prime(30) == False
    assert is_prime(31) == True
    assert is_prime(32) == False
    assert is_prime(33) == False
    assert is_prime(34) == False
    assert is_prime(35) == False
    assert is_prime(36) == False
    assert is_prime(37) == True
    assert is_prime(38) == False
    assert is_prime(39) == False
    assert is_prime(40) == False
    assert is_prime(41) == True

    assert is_prime(1) == False
    assert is_prime(2) == True
    assert is_prime(3) == True
    assert is_prime(4) == False
    assert is_prime(5) == True
    assert is_prime(6) == False
    assert is_prime(7) == True
    assert is_prime(8) == False
    assert is_prime(9) == False
    assert is_prime(10) == False
    assert is_prime(11) == True
    assert is_prime(12) == False
    assert is_prime(13) == True
    assert is_prime(14) == False
    assert is_prime(15) == False
    assert is_prime(16) == False
    assert is_prime(17) == True
    assert is_prime(18) == False
    assert is_prime(19) == True
    assert is_prime(20) == False
    assert is_prime(21) == False
    assert is_prime(22) == False
    assert is_prime(23) == True
    assert is_prime(24) == False
    assert is_prime(25) == False
    assert is_prime(26) == False
    assert is_prime(27) == False
    assert is_prime(28) == False
    assert is_prime(29) == True
    assert is_prime(30) == False

